/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcoin_sigma_PublicCoin */

#ifndef _Included_com_zcoin_sigma_PublicCoin
#define _Included_com_zcoin_sigma_PublicCoin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcoin_sigma_PublicCoin
 * Method:    jCreatePublicCoin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PublicCoin_jCreatePublicCoin
  (JNIEnv *, jclass);

/*
 * Class:     com_zcoin_sigma_PublicCoin
 * Method:    jCreatePublicCoinFromGroupElementAndDenomination
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PublicCoin_jCreatePublicCoinFromGroupElementAndDenomination
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zcoin_sigma_PublicCoin
 * Method:    jGetValue
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PublicCoin_jGetValue
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PublicCoin
 * Method:    jGetDenomination
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PublicCoin_jGetDenomination
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PublicCoin
 * Method:    jEqualOperator
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zcoin_sigma_PublicCoin_jOperatorEqual
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zcoin_sigma_PublicCoin
 * Method:    jNotEqualOperator
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zcoin_sigma_PublicCoin_jOperatorNotEqual
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
