/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcoin_sigma_CoinSpend */

#ifndef _Included_com_zcoin_sigma_CoinSpend
#define _Included_com_zcoin_sigma_CoinSpend
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jCreateCoinSpend
 * Signature: (JJ[JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_CoinSpend_jCreateCoinSpend
  (JNIEnv *, jclass, jlong, jlong, jlongArray, jlong);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jUpdateMetaData
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_CoinSpend_jUpdateMetaData
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jGetCoinSerialNumber
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_CoinSpend_jGetCoinSerialNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jGetDenomination
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_CoinSpend_jGetDenomination
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jSetVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_CoinSpend_jSetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jGetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcoin_sigma_CoinSpend_jGetVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jHasValidSerial
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_zcoin_sigma_CoinSpend_jHasValidSerial
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_CoinSpend
 * Method:    jVerify
 * Signature: ([JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_zcoin_sigma_CoinSpend_jVerify
  (JNIEnv *, jobject, jlongArray, jlong);

#ifdef __cplusplus
}
#endif
#endif
