/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcoin_sigma_Sigma */

#ifndef SIGMAANDROIDWRAPPER_COM_ZCOIN_SIGMA_SIGMA_H
#define SIGMAANDROIDWRAPPER_COM_ZCOIN_SIGMA_SIGMA_H
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_zcoin_sigma_Sigma
* Method:    jCreateMintCommitment
* Signature: (JJJ)J
*/
JNIEXPORT jstring JNICALL Java_com_zcoin_sigma_Sigma_jCreateMintCommitment
        (JNIEnv *, jclass, jlong, jstring, jint);

/*
* Class:     com_zcoin_sigma_Sigma
* Method:    jCreateSpendProof
* Signature: (JJJJJ[JJJJ)J
*/
JNIEXPORT jstring JNICALL Java_com_zcoin_sigma_Sigma_jCreateSpendProof
        (JNIEnv *, jclass, jlong, jstring, jint, jobjectArray, jint, jstring, jstring);

/*
* Class:     com_zcoin_sigma_Sigma
* Method:    jGetSerialNumber
* Signature: (JJJ)J
*/
JNIEXPORT jstring JNICALL Java_com_zcoin_sigma_Sigma_jGetSerialNumber
        (JNIEnv *, jclass, jlong, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif //SIGMAANDROIDWRAPPER_COM_ZCOIN_SIGMA_SIGMA_H
