/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcoin_sigma_PrivateCoin */

#ifndef _Included_com_zcoin_sigma_PrivateCoin
#define _Included_com_zcoin_sigma_PrivateCoin
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jCreatePrivateCoinFromParamsAndDenomination
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PrivateCoin_jCreatePrivateCoinFromParamsAndDenomination
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jCreatePrivateCoinFromParamsAndDenomination
 * Signature: (JJV)J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PrivateCoin_jCreatePrivateCoinFromParamsAndDenominationAndValue
        (JNIEnv *, jclass, jlong, jlong, jint);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetParams
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PrivateCoin_jGetParams
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetPublicCoin
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PrivateCoin_jGetPublicCoin
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetSerialNumber
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PrivateCoin_jGetSerialNumber
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetRandomness
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_PrivateCoin_jGetRandomness
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetVersion
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_zcoin_sigma_PrivateCoin_jGetVersion
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jSetPublicCoin
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_PrivateCoin_jSetPublicCoin
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jSetRandomness
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_PrivateCoin_jSetRandomness
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jSetSerialNumber
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_PrivateCoin_jSetSerialNumber
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jSetVersion
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_PrivateCoin_jSetVersion
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetEcdsaSeckey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jbyteArray JNICALL Java_com_zcoin_sigma_PrivateCoin_jGetEcdsaSeckey
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_PrivateCoin
 * Method:    jGetEcdsaSeckey
 * Signature: ()
 */
JNIEXPORT void JNICALL Java_com_zcoin_sigma_PrivateCoin_jSetEcdsaSeckey
        (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
