/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcoin_sigma_Params */

#ifndef _Included_com_zcoin_sigma_Params
#define _Included_com_zcoin_sigma_Params
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zcoin_sigma_Params
 * Method:    jGetDefault
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_Params_jGetDefault
  (JNIEnv *, jclass);

/*
 * Class:     com_zcoin_sigma_Params
 * Method:    jGet_g
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_Params_jGet_1g
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_Params
 * Method:    jGet_h0
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_Params_jGet_1h0
  (JNIEnv *, jobject);

/*
 * Class:     com_zcoin_sigma_Params
 * Method:    jGet_h
 * Signature: ()[J
 */
JNIEXPORT jlongArray JNICALL Java_com_zcoin_sigma_Params_jGet_1h
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
