/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zcoin_sigma_SigmaPrimitives */

#ifndef _Included_com_zcoin_sigma_SigmaPrimitives
#define _Included_com_zcoin_sigma_SigmaPrimitives
#ifdef __cplusplus
extern "C" {
#endif

/*
* Class:     com_zcoin_sigma_SigmaPrimitives
* Method:    jCommit
* Signature: (JJJJ)J
*/
JNIEXPORT jlong JNICALL Java_com_zcoin_sigma_SigmaPrimitives_jCommit
        (JNIEnv *, jclass, jlong, jlong, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
